# Generated by Django 3.1.4 on 2020-12-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerimage',
            name='header_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='headerimage',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Mainslider'),
        ),
    ]
