# Generated by Django 3.1.4 on 2020-12-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201230_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerimage',
            name='header_url',
        ),
        migrations.RemoveField(
            model_name='services',
            name='services_url',
        ),
    ]
